apiVersion: v1
name: jena-es
description: A Helm chart Jena-ES (based on Apache Jena)
version: 0.4.2
appVersion: "4.0.0"
home: http://jena.apache.org/
icon: http://jena.apache.org/images/jena-logo/jena-logo-jumbotron.png
maintainers:
- name: chinook25
- name: sidohaakma
