apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ template "mcda.fullname" . }}
  labels:
    app: {{ template "mcda.name" . }}
    chart: {{ template "mcda.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  api-key: {{ .Values.patavi.apiKey | b64enc | quote }}
  google-key: {{ .Values.mcda.googleKey | b64enc | quote }}
  google-secret: {{ .Values.mcda.googleSecret | b64enc | quote }}
  cookie-secret: {{ .Values.mcda.cookieSecret | b64enc | quote }}