apiVersion: v1
name: nct-import
description: A Helm chart for the drugis NCT importer
version: 0.1.0
appVersion: "0.2.2"
home: https://github.com/drugis/trialverse-ctgov-import
icon: https://avatars.githubusercontent.com/u/3798208?s=200&v=4
maintainers:
- name: chinook25
- name: sidohaakma
