apiVersion: v1
name: mcda
description: A Helm chart for MCDA service
version: 0.8.2
appVersion: "1.1.0"
icon: https://raw.githubusercontent.com/drugis/mcda-elicitation-web/develop/public/img/favicon.png
maintainers:
- name: chinook25
- name: sidohaakma
