apiVersion: v1
name: patavi-server
description: A Helm chart for the Patavi server
version: 0.1.0
appVersion: "1.0.0"
icon: https://github.com/drugis/patavi/raw/master/server/public/img/patavi_small.png
maintainers:
- name: chinook25
- name: sidohaakma
