apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ template "gemtc.fullname" . }}
  labels:
    app: {{ template "gemtc.name" . }}
    chart: {{ template "gemtc.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  api-key: {{ .Values.patavi.apiKey | b64enc | quote }}
  google-key: {{ .Values.gemtc.googleKey | b64enc | quote }}
  google-secret: {{ .Values.gemtc.googleSecret | b64enc | quote }}
  cookie-secret: {{ .Values.gemtc.cookieSecret | b64enc | quote }}
  database-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{- if .Values.gemtc.enterprise.enabled }}
  admin-password: {{ .Values.gemtc.enterprise.adminPassword | b64enc | quote }}
  github-access-token: {{ .Values.gemtc.enterprise.githubAccessToken | b64enc | quote }}
  {{- end }}
