apiVersion: v1
name: gemtc
description: A Helm chart for GemTC service
version: 0.6.3
appVersion: "0.10.4"
icon: https://raw.githubusercontent.com/drugis/gemtc-web/develop/public/img/favicon.png
maintainers:
- name: chinook25
- name: sidohaakma
